
/*per connectar a la bd root dins el SHELL:
SHELL>mysql --host=localhost --user=root --password=anderssenvsk12 escacsvdt
*/

/*per connectar a la bd escacsvdt dins el SHELL:
SHELL>mysql --host=localhost --user=escacsvdt --password=escacsvdt escacsvdt
*/

/*-------------------------------INICI executar des de BDVAIO-------------------------------*/
/*creem l'usuari escacsvdt*/
CREATE USER 'escacsvdt'@'%' IDENTIFIED BY 'escacsvdt';

/*aplicar privilegis a l'usuari escacsvdt*/
GRANT ALL PRIVILEGES ON *.* 
	TO 'escacsvdt'@'%' 
	IDENTIFIED BY 'escacsvdt' 
	WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
FLUSH PRIVILEGES;
	
/*creem base de dades escacsvdt*/
CREATE DATABASE escacsvdt
  DEFAULT CHARACTER SET 'utf8'
  DEFAULT COLLATE 'utf8_general_ci';
/*--------------------------------FI executar des de BDVAIO--------------------------------*/

USE escacsvdt;

DROP TABLE IF EXISTS PARTIDA;
DROP TABLE IF EXISTS JUGADESOBERTURA;
DROP TABLE IF EXISTS JUGADESGRAELLA;
DROP TABLE IF EXISTS HISTORIALJUGADOR;
DROP TABLE IF EXISTS LOGS;
DROP TABLE IF EXISTS OBERTURA;
DROP TABLE IF EXISTS GRAELLA;
DROP TABLE IF EXISTS REPTE;
DROP TABLE IF EXISTS JUGADOR;


CREATE TABLE IF NOT EXISTS JUGADOR (  
  ID INT (3) NOT NULL AUTO_INCREMENT,
  NOM VARCHAR (50) NOT NULL,
  COGNOMS VARCHAR (100) NOT NULL,
  NICK VARCHAR (50) DEFAULT 'Invitat ' NOT NULL, /*si NO és del Club Escacs VDT, es dirà "Invitat X" (X depenent dels Invitats que hi hagi) */
  PASSWORD VARCHAR (10) DEFAULT 'demo' NOT NULL, /*si NO és del Club Escacs VDT, el password serà "demo"*/
  HORAULTIMLOGIN TIMESTAMP NOT NULL, 
  DIRECCIO VARCHAR (100),
  POBLACIO VARCHAR (50),
  CP VARCHAR (5),
  PROVINCIA VARCHAR (50),
  TELEFON VARCHAR (15),
  EMAIL VARCHAR (50),
  ACTIU INT (1) DEFAULT 0, /*si és 0, està de baixa*/
  PERFIL INT (1) DEFAULT 1, /*si és 1, és un jugador pertanyent a Club Escacs VDT, si és Invitat serà 0 !!!*/
  ELO INT (4) DEFAULT 0,
  IP VARCHAR (50),
  PORT VARCHAR (5),
  ESTAT INT (1) DEFAULT -1, /*desconnectat=-1, lliure=0, reptant=1, jugant=2*/
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS HISTORIALJUGADOR (
  ID INT (6) NOT NULL AUTO_INCREMENT,
  IDJUGADOR INT (3) NOT NULL,
  NUM_HISTORIAL INT (6) NOT NULL,
  HORALOGIN TIMESTAMP NOT NULL,
  ELO INT (4) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (IDJUGADOR) REFERENCES JUGADOR (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS GRAELLA (
  ID INT(6) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS JUGADESGRAELLA (
  ID INT (6) NOT NULL AUTO_INCREMENT,
  IDGRAELLA INT (6) NOT NULL,
  NUMJUGADA INT (3) NOT NULL,
  JUGADAORIGENBLANQUES VARCHAR (5) NOT NULL,
  JUGADAORDESTIBLANQUES VARCHAR (5) NOT NULL,
  JUGADAORIGENNEGRES VARCHAR (5) NOT NULL,
  JUGADADESTINEGRES VARCHAR (5) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (IDGRAELLA) REFERENCES GRAELLA (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS OBERTURA (
  ID INT (3) NOT NULL AUTO_INCREMENT,
  NOM VARCHAR (100) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

  
CREATE TABLE IF NOT EXISTS JUGADESOBERTURA (
  ID INT (6) NOT NULL AUTO_INCREMENT,
  IDOBERTURA INT (3) NOT NULL,
  NUMJUGADA INT (3) NOT NULL,
  JUGADAORIGENBLANQUES VARCHAR (5) NOT NULL,
  JUGADAORDESTIBLANQUES VARCHAR (5) NOT NULL,
  JUGADAORIGENNEGRES VARCHAR (5) NOT NULL,
  JUGADADESTINEGRES VARCHAR (5) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (IDOBERTURA) REFERENCES OBERTURA (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS REPTE (
  ID INT (6) NOT NULL AUTO_INCREMENT,
  IDJUGADORREPTADOR INT (3) NOT NULL,
  IDJUGADORREPTAT INT (3),
  COLORJUGADORREPTADOR VARCHAR(1) NOT NULL,
  HORAINICI TIMESTAMP NOT NULL,
  TEMPS INT (6) NOT NULL, /*en segons!!!*/
  TEMPSINCREMENT INT (3) NOT NULL, /*en segons!!!*/
  AMBEVALUACIOELO INT (1) DEFAULT 0 NOT NULL, 
  ESTAT INT (1) DEFAULT 0 NOT NULL, /*cancel·lat=-1, pendent=0, acceptat=1*/
  DINSSALAJUGADORREPTADOR INT (1),
  DINSSALAJUGADORREPTAT INT (1),
  PRIMARY KEY (ID),
  FOREIGN KEY (IDJUGADORREPTADOR) REFERENCES JUGADOR (ID),
  FOREIGN KEY (IDJUGADORREPTAT) REFERENCES JUGADOR (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS PARTIDA (
  ID INT (6) NOT NULL AUTO_INCREMENT,
  IDREPTE INT (6) NOT NULL,
  IDJUGADORBLANQUES INT (3) NOT NULL,
  IDJUGADORNEGRES INT (3) NOT NULL,
  HORAINICI TIMESTAMP NOT NULL,
  TEMPS INT (6) NOT NULL, /*en segons!!!*/
  TEMPSINCREMENT INT (3) NOT NULL, /*en segons!!!*/
  AMBEVALUACIOELO INT (1) DEFAULT 0 NOT NULL,
  IDGRAELLA INT (6), 
  IDOBERTURA INT (3),
  ESTAT INT (1) DEFAULT 0 NOT NULL, /*cancel·lada=-1, jugant=0, ajornada=1, finalitzada=2*/
  RESULTAT INT (1), /*blanques=1, empat=2, negres=3*/
  PRIMARY KEY (ID),
  FOREIGN KEY (IDREPTE) REFERENCES REPTE (ID),
  FOREIGN KEY (IDJUGADORBLANQUES) REFERENCES JUGADOR (ID),
  FOREIGN KEY (IDJUGADORNEGRES) REFERENCES JUGADOR (ID),
  FOREIGN KEY (IDGRAELLA) REFERENCES GRAELLA (ID),
  FOREIGN KEY (IDOBERTURA) REFERENCES OBERTURA (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS POSICIOTAULER (
  ID INT (6) NOT NULL AUTO_INCREMENT,
  IDPARTIDA INT (6) NOT NULL,
  NUMJUGADA INT (3) NOT NULL,
  COLORULTIMAJUGADA VARCHAR(1) NOT NULL, /*posició després de realitzar la jugada del color*/
  POSICIO VARCHAR(1000) NOT NULL, /*guardem la posició de les peces al tauler, separat per ','*/
  PRIMARY KEY (ID),
  FOREIGN KEY (IDPARTIDA) REFERENCES PARTIDA (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;