----------------------------------INICI executar des de BDVAIO----------------------------------
CREATE USER escacsvdt IDENTIFIED BY escacsvdt;


--aplicar privilegis a l'usuari ESCACSVDT
GRANT CONNECT, CREATE TABLE, CREATE PROCEDURE, ALTER ANY TABLE, ALTER ANY PROCEDURE, DROP ANY TABLE, DROP ANY PROCEDURE TO escacsvdt;
GRANT RESOURCE TO escacsvdt;
GRANT CREATE SESSION TO escacsvdt;
GRANT CREATE SEQUENCE TO escacsvdt;
GRANT SELECT, INSERT, UPDATE, DELETE ON escacsvdt.GRAELLA TO escacsvdt;
GRANT SELECT, INSERT, UPDATE, DELETE ON escacsvdt.JUGADESGRAELLA TO escacsvdt;
GRANT SELECT, INSERT, UPDATE, DELETE ON escacsvdt.JUGADESOBERTURA TO escacsvdt;
GRANT SELECT, INSERT, UPDATE, DELETE ON escacsvdt.JUGADOR TO escacsvdt;
GRANT SELECT, INSERT, UPDATE, DELETE ON escacsvdt.HISTORIALJUGADOR TO escacsvdt;
GRANT SELECT, INSERT, UPDATE, DELETE ON escacsvdt.OBERTURA TO escacsvdt;
GRANT SELECT, INSERT, UPDATE, DELETE ON escacsvdt.PARTIDA TO escacsvdt;
----------------------------------FI executar des de BDVAIO----------------------------------


DROP TABLE PARTIDA;
DROP TABLE JUGADESOBERTURA;
DROP TABLE JUGADESGRAELLA;
DROP TABLE HISTORIALJUGADOR;
DROP TABLE LOGS;
DROP TABLE OBERTURA;
DROP TABLE GRAELLA;
DROP TABLE REPTE;
DROP TABLE JUGADOR;

DROP SEQUENCE SEQPARTIDA;
DROP SEQUENCE SEQJUGADESOBERTURA;
DROP SEQUENCE SEQGRAELLA;
DROP SEQUENCE SEQJUGADESGRAELLA;
DROP SEQUENCE SEQHISTORIALJUGADOR;
DROP SEQUENCE SEQOBERTURA;
DROP SEQUENCE SEQJUGADOR;
DROP SEQUENCE SEQREPTE;

CREATE TABLE JUGADOR (
  ID NUMBER NOT NULL,
  NOM VARCHAR2 (50) NOT NULL,
  COGNOMS VARCHAR2 (100) NOT NULL,
  NICK VARCHAR2 (50) DEFAULT 'Invitat ' NOT NULL, --si NO és del Club Escacs VDT, es dirà "Invitat X" (X depenent dels Invitats que hi hagi) 
  PASSWORD VARCHAR2 (10) DEFAULT 'demo' NOT NULL, --si NO és del Club Escacs VDT, el password serà "demo"
  HORAULTIMLOGIN TIMESTAMP NOT NULL, 
  DIRECCIO VARCHAR2 (100),
  POBLACIO VARCHAR2 (50),
  CP VARCHAR2 (5),
  PROVINCIA VARCHAR2 (50),
  TELEFON VARCHAR2 (15),
  EMAIL VARCHAR2 (50),
  ACTIU NUMBER DEFAULT 0 NOT NULL, --si és 0, està de baixa
  PERFIL NUMBER(1) NOT NULL, --CLUBVDT NUMBER DEFAULT 0 NOT NULL, --si és 1, és un jugador pertanyent a Club Escacs VDT, si és Invitat serà 0 !!!
  ELO NUMBER DEFAULT 0 NOT NULL,
  IP VARCHAR2(50) NOT NULL,
  PORT VARCHAR2 (5) NOT NULL,
  ESTAT NUMBER DEFAULT -1 NOT NULL, --desconnectat=-1, lliure=0, reptant=1, jugant=2
  CONSTRAINT PK_JUGADOR PRIMARY KEY (ID)
);

CREATE TABLE HISTORIALJUGADOR (
  ID NUMBER NOT NULL,
  IDJUGADOR NUMBER NOT NULL,
  NUM_HISTORIAL NUMBER NOT NULL,
  HORALOGIN TIMESTAMP NOT NULL,
  ELO NUMBER NOT NULL,  
  CONSTRAINT PK_HISTORIALJUGADOR PRIMARY KEY (ID),
  CONSTRAINT FK_HISTORIALJUGADOR_JUGADOR FOREIGN KEY (IDJUGADOR) REFERENCES JUGADOR (ID)
);

CREATE TABLE GRAELLA (
  ID NUMBER NOT NULL,
  CONSTRAINT PK_GRAELLA PRIMARY KEY (ID)
);

CREATE TABLE JUGADESGRAELLA (
  ID NUMBER NOT NULL,
  IDGRAELLA NUMBER NOT NULL,
  NUMJUGADA NUMBER NOT NULL,
  JUGADABLANQUES VARCHAR2 (10) NOT NULL,
  JUGADANEGRES VARCHAR2 (10) NOT NULL,
  CONSTRAINT PK_JUGADESGRAELLA PRIMARY KEY (ID),
  CONSTRAINT FK_JUGADESGRAELLA_GRAELLA FOREIGN KEY (IDGRAELLA) REFERENCES GRAELLA (ID)
);

CREATE TABLE LOGS (
  IDJUGADOR NUMBER NOT NULL,
  DIAHORA DATE NOT NULL,
  CONSTRAINT FK_LOG_JUGADOR FOREIGN KEY (IDJUGADOR) REFERENCES JUGADOR (ID)
);

CREATE TABLE OBERTURA (
  ID NUMBER NOT NULL,
  NOM VARCHAR2 (100) NOT NULL,
  CONSTRAINT PK_OBERTURA PRIMARY KEY (ID)
);

CREATE TABLE JUGADESOBERTURA (
  ID NUMBER NOT NULL,
  IDOBERTURA NUMBER NOT NULL,
  NUMJUGADA NUMBER NOT NULL,
  JUGADABLANQUES VARCHAR2 (10) NOT NULL,
  JUGADANEGRES VARCHAR2 (10) NOT NULL,
  CONSTRAINT PK_JUGADESOBERTURA PRIMARY KEY (ID),
  CONSTRAINT FK_OBERTURA FOREIGN KEY (IDOBERTURA) REFERENCES OBERTURA (ID)
);

CREATE TABLE PARTIDA (
  ID NUMBER NOT NULL,
  IDJUGADORBLANQUES NUMBER NOT NULL,
  IDJUGADORNEGRES NUMBER NOT NULL,
  HORAINICI TIMESTAMP NOT NULL,
  TEMPS NUMBER NOT NULL, --en segons!!!
  TEMPSINCREMENT NUMBER NOT NULL, --en segons!!!
  IDGRAELLA NUMBER NOT NULL, 
  IDOBERTURA NUMBER NOT NULL,
  ESTAT NUMBER DEFAULT 0 NOT NULL, --cancel·lada=-1, finalitzada=0, jugant=1, ajornada=2
  CONSTRAINT PK_PARTIDA PRIMARY KEY (ID),
  CONSTRAINT FK_PARTIDA_JUGADOR_1 FOREIGN KEY (IDJUGADORBLANQUES) REFERENCES JUGADOR (ID),
  CONSTRAINT FK_PARTIDA_JUGADOR_2 FOREIGN KEY (IDJUGADORNEGRES) REFERENCES JUGADOR (ID),
  CONSTRAINT FK_PARTIDA_GRAELLA FOREIGN KEY (IDGRAELLA) REFERENCES GRAELLA (ID),
  CONSTRAINT FK_PARTIDA_OBERTURA FOREIGN KEY (IDOBERTURA) REFERENCES OBERTURA (ID)
);

CREATE TABLE REPTE (
  ID NUMBER NOT NULL,
  IDJUGADORREPTADOR NUMBER NOT NULL,
  IDJUGADORREPTAT NUMBER, --NOT NULL,
  COLORJUGADORREPTADOR VARCHAR2(1) NOT NULL,
  HORAINICI TIMESTAMP NOT NULL,
  TEMPS NUMBER NOT NULL, --en segons!!!
  TEMPSINCREMENT NUMBER NOT NULL, --en segons!!!
  AMBEVALUACIOELO NUMBER DEFAULT 0 NOT NULL, 
  
  --canvi 31/12/2013
  ESTAT NUMBER DEFAULT 0 NOT NULL, --cancel·lat=-1, pendent=0, acceptat=1
  DINSSALAJUGADORREPTADOR NUMBER(1,0),
  DINSSALAJUGADORREPTAT NUMBER(1,0),
  
  CONSTRAINT PK_REPTE PRIMARY KEY (ID),
  CONSTRAINT FK_REPTE_JUGADOR1 FOREIGN KEY (IDJUGADORREPTADOR) REFERENCES JUGADOR (ID),
  CONSTRAINT FK_REPTE_JUGADOR2 FOREIGN KEY (IDJUGADORREPTAT) REFERENCES JUGADOR (ID)
);

CREATE SEQUENCE SEQGRAELLA;
CREATE SEQUENCE SEQHISTORIALJUGADOR;
CREATE SEQUENCE SEQJUGADESGRAELLA;
CREATE SEQUENCE SEQJUGADESOBERTURA;
CREATE SEQUENCE SEQJUGADOR;
CREATE SEQUENCE SEQOBERTURA;
CREATE SEQUENCE SEQPARTIDA;
CREATE SEQUENCE SEQREPTE;